install.packages("learnr")
install.packages("nycflights13")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("knitr")
flights
library(ggplot2)
library(nycflights13)
library(knitr)
library(dplyr)
flights
view(flights)
View(flights)
glimpse(flights)
airlines
kable(airlines)
airlines$name
glimpse(airports)
?flights
